@echo off
setlocal EnableExtensions
title ELFIA store - remove the strays from the repository
REM ============================================================
REM  WHY THIS FILE EXISTS (09-09-2026)
REM
REM  The 09-09 deploy stopped on brand-isolation, and it was RIGHT:
REM
REM    FAIL
REM     - CHANGELOG-1.md:3063: contains agency identity
REM     - CHANGELOG-1.md:3063: contains agency registration
REM     - CHANGELOG-1.md:3063: contains agency bank account
REM     ...105 lines in total
REM
REM  CHANGELOG-1.md is 895 KB of the A2Z PORTAL's changelog, copied into this
REM  folder by a Windows name collision. It carries the agency's identity, its
REM  registration number, its bank account and its internal domains - inside
REM  the shop's repository. Keeping the two brands apart is the whole job of
REM  that guard, and it did it.
REM
REM  WHY .gitignore DID NOT STOP IT. The rules are all there - *-1.md, *-2.ts,
REM  out/, *log.txt - and every one of these files is TRACKED anyway, because
REM  they were committed BEFORE those rules were written. A .gitignore rule has
REM  no effect on a file git already tracks. It never had.
REM
REM  That is also why `git check-ignore` reported nothing and the guards kept
REM  reading them: git does not consider a tracked file ignored.
REM
REM  WHAT THIS DOES. Stops git tracking each stray, deletes the copies from the
REM  disk, and makes one ordinary commit. No history is rewritten and nothing
REM  is pushed - run PUSH.bat afterwards as usual.
REM ============================================================

cd /d "%~dp0"

if not exist ".git" (
  echo   [X] This is not the store folder - no .git here.
  echo       Put this file in C:\Users\Alif\Desktop\elfiaofficialstore and run it there.
  pause
  exit /b 1
)

echo.
echo   REMOVE THE STRAYS FROM THE ELFIA STORE REPOSITORY
echo   =================================================
echo.
echo   These are tracked by git today and should never have been:
echo.
echo     CHANGELOG-1.md        the A2Z portal's changelog - agency identity,
echo                           registration number and BANK ACCOUNT
echo     package-1.json        a copy of the portal's package.json
echo     worker\src\index-1.ts a copy of the portal's worker (already emptied)
echo     worker\src\index-2.ts the second copy (already emptied)
echo     out\                  build output - regenerated by every build
echo     deploy-log.txt        local run logs
echo     go-live-log.txt
echo     push-log.txt
echo.
echo   Each is already named in .gitignore. The rules never applied because
echo   the files were committed before those rules existed.
echo.
echo   Nothing is pushed and no history is rewritten. One normal commit.
echo.
set /p GO=  Type YES to continue:
if /I not "%GO%"=="YES" (
  echo   Nothing was changed.
  pause
  exit /b 0
)

echo.
echo   [1/3] Telling git to stop tracking them...
for %%F in ("CHANGELOG-1.md" "package-1.json" "deploy-log.txt" "go-live-log.txt" "push-log.txt" "worker/src/index-1.ts" "worker/src/index-2.ts") do (
  git rm --cached --quiet --ignore-unmatch %%F
)
git rm -r --cached --quiet --ignore-unmatch out

echo   [2/3] Deleting the copies from this folder...
REM  del, not git rm, so a file git never tracked still goes.
if exist "CHANGELOG-1.md"        del /f /q "CHANGELOG-1.md"
if exist "package-1.json"        del /f /q "package-1.json"
if exist "deploy-log.txt"        del /f /q "deploy-log.txt"
if exist "go-live-log.txt"       del /f /q "go-live-log.txt"
if exist "push-log.txt"          del /f /q "push-log.txt"
if exist "worker\src\index-1.ts" del /f /q "worker\src\index-1.ts"
if exist "worker\src\index-2.ts" del /f /q "worker\src\index-2.ts"
REM  out\ is rebuilt by `npx next build` on the very next deploy.
if exist "out" rmdir /s /q "out"

echo   [3/3] Recording it...
git commit --quiet -m "Remove strays that predate .gitignore (portal changelog, duplicate copies, build output, logs)"
if errorlevel 1 (
  echo.
  echo   Nothing needed committing - they were already out.
) else (
  echo   Committed.
)

echo.
echo   ============================================
echo    DONE. Now run PUSH.bat - the store should
echo    publish this time.
echo   ============================================
echo.
echo   ONE THING THIS CANNOT DO: those files are still in the repository's
echo   PAST COMMITS. This stops them going forward; it does not erase what is
echo   already in the history. If that repository is public, or shared with
echo   anyone outside the company, treat the bank account and registration
echo   number in CHANGELOG-1.md as exposed and act on that separately.
echo.
pause
